### ISSUE TITLE
Implement critical failure

### ISSUE THREAD

**Issue by djt5119** [TheFifthRider/simply-roleplaying-webapp#17]
## Summary
While the gods of luck can bless you and grant you critical success, sometimes you might also fall from their favor and that's where critical failures come into play. Although I agree with you that they aren't super fun for the player, I feel like they are a necessary part of the game to balance out the strength of critical success. 

## Associated Modules
Critical Success

## Possible Solutions
* Only roll to confirm critical failure if a PC or NPC misses the DC of a check by some large margin

**Comment by TheFifthRider** [comment]
Implemented as a part of the Combat Update in the new skill system. Checks that fail by 10 or more or succeed by 10 or more are considered "critical" or "dramatic" failures/successes, respectively.
